package summarizer

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/sashabaranov/go-openai"
)

func (ts *TextSummarizer) getOpenAIClient() (*openai.Client, error) {
	ts.clientMutex.Lock()
	defer ts.clientMutex.Unlock()

	if ts.openAIClient != nil {
		return ts.openAIClient, nil
	}

	if ts.openAIKey == "" {
		return nil, errors.New("api key is required for openAI summarization")
	}

	// Create client with custom configuration if basedURL is specified

	if ts.openAIBaseURL != "" {
		config := openai.DefaultConfig(ts.openAIKey)

		config.BaseURL = ts.openAIBaseURL

		ts.openAIClient = openai.NewClientWithConfig(config)
	} else {
		ts.openAIClient = openai.NewClient(ts.openAIKey)
	}

	return ts.openAIClient, nil
}

func (ts *TextSummarizer) generateOpenAISummary() (string, error) {
	lengthInstruction := fmt.Sprintf("Create a summary that is approximetly %%d of the original text length.", int(ts.targetPercentage))

	client, err := ts.getOpenAIClient()

	if err != nil {
		log.Printf("Error in generateOpenAISummary: %v", err)
		return "", err
	}

	resp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: ts.openAIModel,
			Messages: []openai.ChatCompletionMessage{
				{
					Role: openai.ChatMessageRoleSystem,
					Content: "You are sophisticated text summarization system. Create a coherent and consize summary that captures main points and preserves the overall meaning of the text" +
						"Generate completely new sentences rather than extracting new ones." + lengthInstruction,
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: ts.text,
				},
			},
			Temperature: 0.3, // Lower temperature for more focused
		},
	)
	if err != nil {
		log.Printf("Error in generateOpenAISummary: %v", err)
		return "", fmt.Errorf("error generating OpenAI summary: %v", err)
	}

	if len(resp.Choices) == 0 {
		log.Printf("no summary generated by openAI")
		return "", errors.New("no summary generated by openAI")
	}

	return resp.Choices[0].Message.Content, nil
}
